<a href="https://colab.research.google.com/github/rebecca-gruver/rebecca-gruver/blob/master/ais_data_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/AIS_2020_01_01.csv'
df = pd.read_csv(path)

In [ ]:
df

MMSI         BaseDateTime  ...  Cargo  TranscieverClass
0        367149340  2020-01-01T00:00:00  ...   31.0                 B
1        367687520  2020-01-01T00:00:00  ...    NaN                 B
2        367368170  2020-01-01T00:00:03  ...   32.0                 B
3        367007980  2020-01-01T00:00:05  ...    NaN                 B
4        367538940  2020-01-01T00:00:05  ...    NaN                 B
...            ...                  ...  ...    ...               ...
7033450  366967640  2020-01-01T23:59:50  ...   31.0                 B
7033451  367092150  2020-01-01T23:59:52  ...    NaN                 B
7033452  366986330  2020-01-01T23:59:52  ...    NaN                 B
7033453  366998040  2020-01-01T23:59:55  ...   52.0                 B
7033454  441343000  2020-01-01T23:59:59  ...   70.0                 B

[7033455 rows x 17 columns]

In [ ]:
df = df.dropna()

In [ ]:
df

MMSI         BaseDateTime  ...  Cargo  TranscieverClass
9        477628100  2020-01-01T00:00:01  ...   70.0                 B
13       367091120  2020-01-01T00:00:04  ...   52.0                 B
17       538002845  2020-01-01T00:00:10  ...   89.0                 B
24       367528690  2020-01-01T00:00:02  ...    2.0                 B
29       477214900  2020-01-01T00:00:06  ...   80.0                 B
...            ...                  ...  ...    ...               ...
7033378  403579000  2020-01-01T23:58:52  ...   89.0                 A
7033415  338217000  2020-01-01T23:57:28  ...   70.0                 A
7033430  368555000  2020-01-01T23:59:59  ...   30.0                 B
7033441  367602520  2020-01-01T23:58:49  ...    0.0                 B
7033454  441343000  2020-01-01T23:59:59  ...   70.0                 B

[788157 rows x 17 columns]

In [ ]:
grouped_df = df.groupby('VesselName')

In [ ]:
grouped_lists = grouped_df['LAT'].apply(list)

In [ ]:
grouped_lists = grouped_lists.reset_index()

In [ ]:
grouped_lists

VesselName                                                LAT
0       A J MCALLISTER  [37.81453, 37.81788, 37.82447, 37.828379999999...
1       ABIGAIL CLAIRE  [30.49199, 30.493859999999998, 30.49751, 30.49...
2              ACADIAN  [42.992670000000004, 42.992740000000005, 42.99...
3          ACHIEVEMENT  [28.234, 28.2526, 28.163590000000003, 28.11454...
4        ADAM F KRAUSE  [39.269729999999996, 39.269729999999996, 39.26...
...                ...                                                ...
1296  ZACHERY REINAUER  [42.3804, 42.380359999999996, 42.3803599999999...
1297            ZENITH  [26.13944, 26.13944, 26.13944, 26.13945, 26.13...
1298     ZIM ROTTERDAM  [25.80712, 25.847479999999997, 25.87525, 25.88...
1299    ZOOM ZOOM ZOOM                     [25.49713, 25.497139999999998]
1300         \ADY0THEO  [32.01319, 32.01178, 32.00963, 32.00934, 32.00...

[1301 rows x 2 columns]

In [ ]:
all_data = df['LAT'].values.astype(float)

In [ ]:
print(all_data)

[36.80096 39.89587 26.0842  ... 47.6304  32.85486 34.28028]


In [ ]:
len(all_data)

788157

In [ ]:
all_data

array([36.80096, 39.89587, 26.0842 , ..., 47.6304 , 32.85486, 34.28028])

In [ ]:
test_data_size = 8157

In [ ]:
train_data = all_data[:-test_data_size]
test_data = all_data[-test_data_size:]

In [ ]:
print(len(train_data))

780000


In [ ]:
print(train_data)

[36.80096 39.89587 26.0842  ... 41.97533 40.53365 29.81467]


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1,1))
train_data_normalized = scaler.fit_transform(train_data.reshape(-1,1))

In [ ]:
print(train_data_normalized[:5])
print(train_data_normalized[-5:])

[[-0.06130338]
 [ 0.07383373]
 [-0.5292433 ]
 [ 0.68556545]
 [ 0.433439  ]]
[[-0.19480351]
 [-0.3617636 ]
 [ 0.16463191]
 [ 0.10168195]
 [-0.3663549 ]]


In [ ]:
import torch
train_data_normalized = torch.FloatTensor(train_data_normalized).view(-1).cuda()

In [ ]:
train_window = 24

In [ ]:
def create_inout_sequences(input_data, tw):
  inout_seq = []
  L = len(input_data)
  for i in range(L-tw):
    train_seq = input_data[i:i+tw]
    train_label = input_data[i+tw:i+tw+1]
    inout_seq.append((train_seq, train_label))
  return inout_seq 

In [ ]:
train_inout_seq = create_inout_sequences(train_data_normalized,train_window)

In [ ]:
train_inout_seq[:5]

[(tensor([-0.0613,  0.0738, -0.5292,  0.6856,  0.4334, -0.0194, -0.0597, -0.3869,
          -0.0190,  0.0433,  0.3251, -0.4939,  0.4689,  0.0743, -0.3620,  0.4126,
           0.1016,  0.1063, -0.5261, -0.3697,  0.4364, -0.2336,  0.0542, -0.4111],
         device='cuda:0'), tensor([-0.3487], device='cuda:0')),
 (tensor([ 0.0738, -0.5292,  0.6856,  0.4334, -0.0194, -0.0597, -0.3869, -0.0190,
           0.0433,  0.3251, -0.4939,  0.4689,  0.0743, -0.3620,  0.4126,  0.1016,
           0.1063, -0.5261, -0.3697,  0.4364, -0.2336,  0.0542, -0.4111, -0.3487],
         device='cuda:0'),
  tensor([0.1498], device='cuda:0')),
 (tensor([-0.5292,  0.6856,  0.4334, -0.0194, -0.0597, -0.3869, -0.0190,  0.0433,
           0.3251, -0.4939,  0.4689,  0.0743, -0.3620,  0.4126,  0.1016,  0.1063,
          -0.5261, -0.3697,  0.4364, -0.2336,  0.0542, -0.4111, -0.3487,  0.1498],
         device='cuda:0'), tensor([-0.4886], device='cuda:0')),
 (tensor([ 0.6856,  0.4334, -0.0194, -0.0597, -0.3869, -0.0190,  0

In [ ]:
import torch.nn as nn
class LSTM(nn.Module):
    def __init__(self, input_size=1, hidden_layer_size=100, output_size=1):
        super().__init__()
        self.hidden_layer_size = hidden_layer_size

        self.lstm = nn.LSTM(input_size, hidden_layer_size)

        self.linear = nn.Linear(hidden_layer_size, output_size)

        self.hidden_cell = (torch.zeros(1,1,self.hidden_layer_size),
                            torch.zeros(1,1,self.hidden_layer_size))

    def forward(self, input_seq):
        lstm_out, self.hidden_cell = self.lstm(input_seq.view(len(input_seq) ,1, -1), self.hidden_cell)
        predictions = self.linear(lstm_out.view(len(input_seq), -1))
        return predictions[-1]

In [ ]:
model = LSTM()
model = model.cuda()
loss_function = nn.MSELoss().cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:
print(model)

LSTM(
  (lstm): LSTM(1, 100)
  (linear): Linear(in_features=100, out_features=1, bias=True)
)


In [ ]:

epochs = 150
for i in range(epochs):
    for seq, labels in train_inout_seq:
        optimizer.zero_grad()
        model.hidden_cell = (torch.zeros(1, 1, model.hidden_layer_size).cuda(),
                        torch.zeros(1, 1, model.hidden_layer_size).cuda())

        y_pred = model(seq.cuda())

        single_loss = loss_function(y_pred, labels)
        single_loss.backward()
        optimizer.step()
        torch.save(model.state_dict(),'model_state_'+str(epochs)+'.pt')

    if i%25 == 1:
        print(f'epoch: {i:3} loss: {single_loss.item():10.8f}')

print(f'epoch: {i:3} loss: {single_loss.item():10.10f}')

epoch:   1 loss: 0.05476350


In [ ]:
fut_pred = 24

test_inputs = train_data_normalized[-train_window:].tolist()
print(test_inputs)

[-0.3622683584690094, -0.3537433445453644, -0.3694070279598236, -0.5107496976852417, -0.3562968373298645, -0.05232905596494675, -0.3560138940811157, -0.5002711415290833, -0.36337044835090637, 0.10816565901041031, -0.36153873801231384, 0.1434551626443863, -0.5132359862327576, -0.5131045579910278, -0.3406750559806824, -0.34886953234672546, -0.34886953234672546, -0.3908379077911377, -0.3693402409553528, -0.19480350613594055, -0.361763596534729, 0.1646319031715393, 0.10168194770812988, -0.36635491251945496]


In [ ]:
model.eval()

for i in range(fut_pred):
    seq = torch.FloatTensor(test_inputs[-train_window:])
    with torch.no_grad():
        model.hidden = (torch.zeros(1, 1, model.hidden_layer_size),
                        torch.zeros(1, 1, model.hidden_layer_size))
        test_inputs.append(model(seq).item())

In [ ]:
test_inputs[fut_pred:]

In [ ]:
actual_predictions = scaler.inverse_transform(np.array(test_inputs[train_window:] ).reshape(-1, 1))
print(actual_predictions)

In [ ]:
df

MMSI         BaseDateTime       LAT  ...  Draft  Cargo  TranscieverClass
0       367149340  2020-01-01T00:00:00  29.96476  ...    NaN   31.0                 B
1       367687520  2020-01-01T00:00:00  30.20558  ...    NaN    NaN                 B
2       367368170  2020-01-01T00:00:03  47.53785  ...    NaN   32.0                 B
3       367007980  2020-01-01T00:00:05  37.95154  ...    3.4    NaN                 B
4       367538940  2020-01-01T00:00:05  30.00258  ...    NaN    NaN                 B
...           ...                  ...       ...  ...    ...    ...               ...
229017  367106880  2020-01-01T00:50:18  30.28373  ...    1.5    NaN                 A
229018  369339000  2020-01-01T00:50:12  33.73357  ...   11.2   79.0                 B
229019  244203000  2020-01-01T00:51:47  27.84289  ...    8.3    NaN                 A
229020  338162563  2020-01-01T00:51:50  30.36263  ...    NaN    NaN                 B
229021    3676776                  NaN       NaN  ...    NaN    NaN               NaN

[229022 rows x 17 columns]

In [ ]:
import torch
import torch.nn as nn 
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline 

In [ ]:
df.head()

MMSI         BaseDateTime       LAT  ...  Draft  Cargo  TranscieverClass
0  367149340  2020-01-01T00:00:00  29.96476  ...    NaN   31.0                 B
1  367687520  2020-01-01T00:00:00  30.20558  ...    NaN    NaN                 B
2  367368170  2020-01-01T00:00:03  47.53785  ...    NaN   32.0                 B
3  367007980  2020-01-01T00:00:05  37.95154  ...    3.4    NaN                 B
4  367538940  2020-01-01T00:00:05  30.00258  ...    NaN    NaN                 B

[5 rows x 17 columns]

In [ ]:
df.shape

(229022, 17)

In [ ]:
df.columns

Index(['MMSI', 'BaseDateTime', 'LAT', 'LON', 'SOG', 'COG', 'Heading',
       'VesselName', 'IMO', 'CallSign', 'VesselType', 'Status', 'Length',
       'Width', 'Draft', 'Cargo', 'TranscieverClass'],
      dtype='object')

In [ ]:
229022-200000

29022

In [ ]:
vessel_data = df['VesselName']

In [ ]:
test_data_size = 29022
train_data = vessel_data[:-test_data_size]
test_data = vessel_data[-test_data_size:]

In [ ]:
print(len(train_data))
print(len(test_data))

200000
29022


In [ ]:
print(test_data)

200000            DAUNTLESS
200001       MISS GABRIELLA
200002            UNBRIDLED
200003              JAMES T
200004         CG BARRACUDA
                ...        
229017            NEW ROADS
229018    PRESIDENT KENNEDY
229019      HAPPY BUCCANEER
229020            BLUE MOON
229021                  NaN
Name: VesselName, Length: 29022, dtype: object
